export default function Head() {
    return (
        <>
            <title>Digital Portfolio</title>
            <meta name="description" content="Generated by create next app" />
        </>
    );
}
