import Contact from "./components/Contact";
import Experience from "./components/Experience";
import HeroSection from "./components/HeroSection";
import Projects from "./components/Projects";
import Skills from "./components/Skills";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Digital Portfolio",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <div className="mx-auto dark:bg-zinc-950">
            <HeroSection />
            <Experience />
            <Skills />
            <Projects />
            <Contact />
        </div>
    );
}
