import Experience from "./components/Experience";
import HeroSection from "./components/HeroSection";
import Skills from "./components/Skills";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <div className="max-w-5xl px-4 mx-auto">
            <HeroSection />
            <Experience />
            <Skills />
        </div>
    );
}
